FROM node:20-slim

WORKDIR /usr/src/app

# Install dependencies required for Prisma and node-gyp
RUN apt-get update -y && apt-get install -y openssl python3 make g++ 

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies with all dev dependencies
RUN npm install

# Generate Prisma Client
RUN npx prisma generate

# Copy the rest of the application
COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]