name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: Docker Login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile.prod
            push: true
            tags: manikdingra/callsure-ai-backend:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
        - name: Configure Docker credentials on EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/callsure-ai-backend:${{ github.sha }}
              docker stop callsurea-ai-backend || true
              docker rm callsurea-ai-backend || true
              docker run -d -p 8080:8080 --name callsurea-ai-backend ${{ secrets.DOCKERHUB_USERNAME }}/callsure-ai-backend:${{ github.sha }}
